### ISSUE TITLE
Crystal addresses [only RAM Location]

### ISSUE THREAD

**Issue by RichardPaulAstley** [wwwwwwzx/gsclua#1]
Hey, as you asked here's the egg address : 

0xDF90 - Egg DVs Location

Tell me if you need any other address for Crystal i'd love to help you o/

Thanks !

**Comment by wwwwwwzx** [comment]
Added in https://github.com/wwwwwwzx/gsclua/commit/d5c3caa8925ea1845b7d73c3cb27991ea8cf87b1. Thanks
