### ISSUE TITLE
Shiny egg question

### ISSUE THREAD

**Issue by KarpMaskReplica** [wwwwwwzx/gsclua#10]
Hey, I'm not sure if I'm running gsc_egg.lua correctly, because running the script as how it's said on README.md (run the script after I put the second parent) doesn't work for me. I run the script when the old man is outside of day care, precisely when he gives options for picking the egg, script works and stops when the egg is shiny, but the first one is not shiny when I hatch it or by using party view to check dv's. The funny thing is next eggs, using the same method are always shiny. That's how the script actually work? If i'm wrong, how's the correct process?

Thanks!

**Comment by wwwwwwzx** [comment]
Same as gen6 RNG, the script is botting the **NEXT** egg you will have. (not the one in old man's hand)
On the other hand, the current egg's dvs (the one in old man's hand or even old man isn't outside of daycare) were already generated when you receive the previous egg or the moment you put the 2nd parent in.

**Comment by KarpMaskReplica** [comment]
Ok, got it. So what's the precise moment to run the script?

**Comment by wwwwwwzx** [comment]
Use [DayCareView](https://github.com/wwwwwwzx/gsclua/blob/master/Viewer/gsc_DayCareView.lua) to see at which moment the egg dvs change when you press A. that's the moment for script.

**Comment by KarpMaskReplica** [comment]
Thank you very much for the help! Now I know the exact moment for the script and don't have to wait for more than one egg.
