### ISSUE TITLE
Egg RNG Pulling 0

### ISSUE THREAD

**Issue by brutalgg** [wwwwwwzx/gsclua#18]
Hello, 

I'm trying to get egg rng working for crystal and i'm running into an issue where the script is pulling 0s for the next egg stat.
[https://media.discordapp.net/attachments/297211485921345536/410585014187851786/Screen_Shot_2018-02-06_at_18.57.05.png](url)
I've tried to use the daycare viewer to capture the moment when the next egg is set and i'm on that dialog but still encountering this. Is it something i need to modify? Thanks.

**Comment by RichardPaulAstley** [comment]
The delay needs some work.

Right here : 

![image](https://user-images.githubusercontent.com/25870563/35894472-1ba8d9c8-0bb3-11e8-8a21-e98492204324.png)
I set it to 150 and was able to do EVERY pokemon with that delay.

**Comment by brutalgg** [comment]
Thanks for your response. I was actually just logging on to comment that I modified that line to 1, 130 and was able to get that to work but this is good information to have.
