### ISSUE TITLE
[Wild] TASing ANY of the Pokemon ?

### ISSUE THREAD

**Issue by RichardPaulAstley** [wwwwwwzx/gsclua#2]
Well, since you have to put a target like this : 
local desired_species = 132 

I wanted to know if there was a way to hunt ANY Pokemon of the route. Just the goal of a Shiny, and if not, if this could be added as an option.

Thanks o/

**Comment by wwwwwwzx** [comment]
You can change the dex number to any pokemon you want. For example, if you want pikachu to be shiny, the change it to 25.

**Comment by RichardPaulAstley** [comment]
Yep that's exactly the thing I don't want haha.
I'm in a zone, I'd like ANY of the wild Pokemon (aka in a route with Ditto, Drowzee etc) I want them all, i don't care. How can I do that ?

Thanks o/
